### PR TITLE
Added paper

### PR DESCRIPTION
**Pull request by KennethEnevoldsen**
Added paper prior to joss submission.

### CODE REVIEW

**Comment by HLasse** [comment]
Do you want feedback on the paper or just for bringing attention to the fact that it's out?

**Comment by KennethEnevoldsen** [comment]
Wanted feedback but already submitted (I assumed you were too busy)

**Comment by HLasse** [comment]
Happy to give it a pass after nips!

**Comment by HLasse** [comment]
Wrote you a message on slack with a link to GDocs with comments 👍

**Pull request merged**
